// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 140936d9277d47fa8580a9b53509ad61c1c5a4bf
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
