// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 98da61f1000b32826539e9410e8c3962741ad61a
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
