// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 140936d9277d47fa8580a9b53509ad61c1c5a4bf
//
pub mod axicdma;
pub mod doe_mbox;
pub mod el2_pic;
pub mod i3c;
pub mod lc;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod primary_flash;
pub mod root_bus;
pub mod secondary_flash;
pub mod sha512_acc;
pub mod soc;
